/* ==========================================================================
   The phrase-first Pre-A1 → early-A1 inventory.
   --------------------------------------------------------------------------
   The beginner bank next door (lessons/beginnerContent.ts) is a set of
   ACTIVITIES: things a tutor can do for four minutes. That was enough to fill
   a lesson and never enough to answer the only question that matters between
   lessons — "which English can this learner actually say?" An activity is not
   a target: it has no meaning, no prerequisites, nothing to be due for review,
   and nothing that can be produced unaided.

   This file is the missing half: one hundred CHUNKS AND SENTENCE FRAMES,
   chosen for what they let a learner do in a real conversation on day one.

   Four rules decided what is in here, in this order:

     1. UTILITY.       Would a real beginner need this in their first month
                       of using English with a human being? "I don't
                       understand" outranks the alphabet.
     2. FREQUENCY.     Spoken frequency, not written. "Really?" earns a slot;
                       "How do you do?" does not.
     3. GENERATIVITY.  A frame with a slot ("I want ___") is worth more than
                       ten memorized sentences, because the learner leaves
                       with a machine rather than a souvenir. 62 of the 100
                       carry a slot on purpose.
     4. TEACHABILITY.  It has to be showable without translation — a gesture,
                       an object, a situation. `show` names which.

   And two things are deliberately absent: grammar terminology (a learner
   meets "I'm going to ___" as one piece of language, never as "the present
   continuous"), and any target whose only value is that it is traditionally
   taught first.

   The ENGLISH here is content the learner hears and says, and is never
   translated. The one localized field is `meaning` — a zero-English learner
   has to be told what a chunk means in a language they have, and every
   locale carries it under `phrase.<id>.meaning`.
   ========================================================================== */

import { PreA1Stage } from '../types'

/** What the chunk lets a learner DO. Drives lesson shape, not vocabulary. */
export type PhraseFunction =
  | 'greeting'
  | 'repair'
  | 'introducing'
  | 'describingSelf'
  | 'wanting'
  | 'asking'
  | 'everyday'
  | 'reacting'
  | 'practical'
  | 'arranging'

/** How the tutor makes the meaning land WITHOUT translating it. */
export type PhraseShow = 'gesture' | 'object' | 'picture' | 'situation' | 'contrast'

export interface PhraseTarget {
  /** Stable forever — evidence, review dates and homework all key on it. */
  id: string
  /**
   * The canonical form the learner stores. `___` marks the substitutable
   * slot: it is the difference between a phrase they can use and a sentence
   * they can recite.
   */
  chunk: string
  /** One complete utterance — what the tutor models and what TTS speaks. */
  say: string
  /** Plain-English meaning. Localized per learner via `phrase.<id>.meaning`. */
  meaning: string
  /** Curriculum unit, 1–10. */
  unit: number
  /** Earliest internal stage this is teachable at. */
  stage: PreA1Stage
  fn: PhraseFunction
  /** Words that fit the slot. Empty for a fixed chunk. */
  slots: string[]
  /** Whole utterances built from the chunk — models, and substitution drill. */
  examples: string[]
  /** Ids that should already be produced with support before this is met. */
  requires: string[]
  /** The natural reply, so the tutor can run a two-line exchange immediately. */
  reply?: string
  show: PhraseShow
  /** Global teaching order. */
  order: number
}

/** Does this target carry a substitutable slot? */
export function isFrame(p: PhraseTarget): boolean {
  return p.chunk.includes('___')
}

/** Fill a frame's slot. A fixed chunk is returned unchanged. */
export function fillSlot(p: PhraseTarget, filler: string): string {
  return p.chunk.includes('___') ? p.chunk.replace('___', filler) : p.chunk
}

/* -------------------------------------------------------------------------- */

type Draft = Omit<PhraseTarget, 'order'>

const UNITS: Draft[][] = [
  /* ======================= 1. Meeting people ============================== *
     The first lesson has to end with the learner having SAID something to a
     person. Everything here works with a wave and a smile behind it, which is
     what makes it teachable to someone with no English at all.                */
  [
    {
      id: 'hello',
      chunk: 'Hello.',
      say: 'Hello.',
      meaning: 'What you say when you meet someone.',
      unit: 1,
      stage: 'P0',
      fn: 'greeting',
      slots: [],
      examples: ['Hello.', 'Hi.', 'Hello, Anna.'],
      requires: [],
      reply: 'Hello!',
      show: 'gesture',
    },
    {
      id: 'goodMorning',
      chunk: 'Good ___.',
      say: 'Good morning.',
      meaning: 'A greeting that says which part of the day it is.',
      unit: 1,
      stage: 'P0',
      fn: 'greeting',
      /* Not 'night': "Good night" is a farewell/bedtime phrase, never a
         greeting on arrival — including it here would teach the opposite of
         what `meaning` promises. */
      slots: ['morning', 'afternoon', 'evening'],
      examples: ['Good morning.', 'Good afternoon.', 'Good evening.'],
      requires: ['hello'],
      reply: 'Good morning!',
      show: 'picture',
    },
    {
      id: 'howAreYou',
      chunk: 'How are you?',
      say: 'How are you?',
      meaning: 'Asking someone if they are well.',
      unit: 1,
      stage: 'P0',
      fn: 'greeting',
      slots: [],
      examples: ['Hello. How are you?', 'Hi! How are you?'],
      requires: ['hello'],
      reply: 'I’m fine, thank you.',
      show: 'situation',
    },
    {
      id: 'imFine',
      chunk: 'I’m fine, thank you.',
      say: 'I’m fine, thank you.',
      meaning: 'The answer to “How are you?” — you are well.',
      unit: 1,
      stage: 'P0',
      fn: 'greeting',
      slots: [],
      examples: ['I’m fine, thank you.', 'I’m good, thanks.', 'I’m OK, thanks.'],
      requires: ['howAreYou'],
      reply: 'And you?',
      show: 'situation',
    },
    {
      id: 'thankYou',
      chunk: 'Thank you.',
      say: 'Thank you.',
      meaning: 'What you say when someone helps you or gives you something.',
      unit: 1,
      stage: 'P0',
      fn: 'greeting',
      slots: [],
      examples: ['Thank you.', 'Thanks.', 'Thank you very much.'],
      requires: [],
      reply: 'You’re welcome.',
      show: 'object',
    },
    {
      id: 'please',
      chunk: 'Please.',
      say: 'Please.',
      meaning: 'The word that turns asking into asking politely.',
      unit: 1,
      stage: 'P0',
      fn: 'greeting',
      slots: [],
      examples: ['Please.', 'Yes, please.', 'Water, please.'],
      requires: [],
      show: 'object',
    },
    {
      id: 'yesNo',
      chunk: 'Yes. / No.',
      say: 'Yes. No.',
      meaning: 'Agreeing, and not agreeing.',
      unit: 1,
      stage: 'P0',
      fn: 'greeting',
      slots: [],
      examples: ['Yes.', 'No.', 'Yes, please.', 'No, thank you.'],
      requires: [],
      show: 'gesture',
    },
    {
      id: 'sorry',
      chunk: 'Sorry.',
      say: 'Sorry.',
      meaning: 'What you say when you make a mistake or bump into someone.',
      unit: 1,
      stage: 'P0',
      fn: 'greeting',
      slots: [],
      examples: ['Sorry.', 'I’m sorry.', 'Sorry, my mistake.'],
      requires: [],
      reply: 'That’s OK.',
      show: 'situation',
    },
    {
      id: 'excuseMe',
      chunk: 'Excuse me.',
      say: 'Excuse me.',
      meaning: 'How you get someone’s attention before you ask them something.',
      unit: 1,
      stage: 'P0',
      fn: 'greeting',
      slots: [],
      examples: ['Excuse me.', 'Excuse me, please.', 'Excuse me — hello?'],
      requires: [],
      reply: 'Yes?',
      show: 'situation',
    },
    {
      id: 'goodbye',
      chunk: 'Goodbye.',
      say: 'Goodbye. See you later.',
      meaning: 'What you say when you leave.',
      unit: 1,
      stage: 'P0',
      fn: 'greeting',
      slots: [],
      examples: ['Goodbye.', 'Bye!', 'See you later.', 'See you tomorrow.'],
      requires: ['hello'],
      reply: 'Bye!',
      show: 'gesture',
    },
  ],

  /* ========================= 2. Repair language =========================== *
     Taught second, and that is the single most important ordering decision in
     this file. Repair language is what keeps a beginner IN the conversation
     instead of nodding through it: without it the learner's only strategies
     are silence and pretending. Every one of these is high-frequency, and
     "What does ___ mean?" and "How do you say ___ in English?" are the two
     most generative frames a beginner can own — they turn every unknown word
     into something the learner can get for themselves.                       */
  [
    {
      id: 'dontUnderstand',
      chunk: 'I don’t understand.',
      say: 'I don’t understand.',
      meaning: 'You did not understand — say this instead of staying quiet.',
      unit: 2,
      stage: 'P0',
      fn: 'repair',
      slots: [],
      examples: ['I don’t understand.', 'Sorry, I don’t understand.'],
      requires: ['sorry'],
      reply: 'No problem. Again:',
      show: 'gesture',
    },
    {
      id: 'sayAgain',
      chunk: 'Can you say that again, please?',
      say: 'Can you say that again, please?',
      meaning: 'Asking someone to repeat what they said.',
      unit: 2,
      stage: 'P0',
      fn: 'repair',
      slots: [],
      examples: ['Can you say that again, please?', 'Again, please?', 'Sorry — again?'],
      requires: ['please'],
      reply: 'Of course.',
      show: 'situation',
    },
    {
      id: 'speakSlowly',
      chunk: 'Can you speak slowly, please?',
      say: 'Can you speak slowly, please?',
      meaning: 'Asking someone to talk more slowly.',
      unit: 2,
      stage: 'P0',
      fn: 'repair',
      slots: [],
      examples: ['Can you speak slowly, please?', 'Slowly, please.', 'A little slower, please.'],
      requires: ['please'],
      reply: 'Sure — slowly.',
      show: 'gesture',
    },
    {
      id: 'whatDoesMean',
      chunk: 'What does ___ mean?',
      say: 'What does “busy” mean?',
      meaning: 'Asking what an English word means.',
      unit: 2,
      stage: 'P1',
      fn: 'repair',
      slots: ['busy', 'ready', 'later', 'this word', 'that'],
      examples: ['What does “busy” mean?', 'What does “ready” mean?', 'What does that mean?'],
      requires: ['dontUnderstand'],
      reply: 'It means…',
      show: 'situation',
    },
    {
      id: 'howDoYouSay',
      chunk: 'How do you say ___ in English?',
      say: 'How do you say this in English?',
      meaning: 'Asking for the English word for something.',
      unit: 2,
      stage: 'P1',
      fn: 'repair',
      slots: ['this', 'that', 'this word'],
      examples: ['How do you say this in English?', 'How do you say that in English?'],
      requires: ['dontUnderstand'],
      reply: 'We say…',
      show: 'object',
    },
    {
      id: 'howSpell',
      chunk: 'How do you spell that?',
      say: 'How do you spell that?',
      meaning: 'Asking for the letters of a word.',
      unit: 2,
      stage: 'P2',
      fn: 'repair',
      slots: [],
      examples: ['How do you spell that?', 'How do you spell your name?'],
      requires: ['howDoYouSay'],
      show: 'situation',
    },
    {
      id: 'dontKnow',
      chunk: 'I don’t know.',
      say: 'I don’t know.',
      meaning: 'You do not have the answer.',
      unit: 2,
      stage: 'P0',
      fn: 'repair',
      slots: [],
      examples: ['I don’t know.', 'Sorry, I don’t know.'],
      requires: [],
      show: 'gesture',
    },
    {
      id: 'oneMoment',
      chunk: 'Just a moment, please.',
      say: 'Just a moment, please.',
      meaning: 'Asking someone to wait while you think or find something.',
      unit: 2,
      stage: 'P1',
      fn: 'repair',
      slots: [],
      examples: ['Just a moment, please.', 'One moment, please.', 'Wait a moment, please.'],
      requires: ['please'],
      show: 'gesture',
    },
    {
      id: 'sorryWhat',
      chunk: 'Sorry, what?',
      say: 'Sorry, what?',
      meaning: 'You did not hear — a short way to ask someone to repeat.',
      unit: 2,
      stage: 'P1',
      fn: 'repair',
      slots: [],
      examples: ['Sorry, what?', 'Sorry — what was that?'],
      requires: ['sorry'],
      show: 'situation',
    },
    {
      id: 'isThisRight',
      chunk: 'Is this right?',
      say: 'Is this right?',
      meaning: 'Checking that what you said or did is correct.',
      unit: 2,
      stage: 'P1',
      fn: 'repair',
      slots: [],
      examples: ['Is this right?', 'Is that right?', 'Like this?'],
      requires: [],
      reply: 'Yes, that’s right.',
      show: 'contrast',
    },
  ],

  /* ========================= 3. Introductions ============================= */
  [
    {
      id: 'myNameIs',
      chunk: 'My name is ___.',
      say: 'My name is Binyamin.',
      meaning: 'Telling someone your name.',
      unit: 3,
      stage: 'P0',
      fn: 'introducing',
      /* The learner's own name is the real filler, every time. These are for
         the substitution drill: swapping in the names of people they actually
         know is what stops "My name is…" being one memorized noise. */
      slots: ['Binyamin', 'Anna', 'Sam', 'Yosef'],
      examples: ['My name is Binyamin.', 'My name is Anna.', 'I’m Anna.'],
      requires: ['hello'],
      reply: 'Nice to meet you.',
      show: 'gesture',
    },
    {
      id: 'whatsYourName',
      chunk: 'What’s your name?',
      say: 'What’s your name?',
      meaning: 'Asking someone their name.',
      unit: 3,
      stage: 'P0',
      fn: 'introducing',
      slots: [],
      examples: ['What’s your name?', 'And what’s your name?'],
      requires: ['myNameIs'],
      reply: 'My name is…',
      show: 'gesture',
    },
    {
      id: 'niceToMeetYou',
      chunk: 'Nice to meet you.',
      say: 'Nice to meet you.',
      meaning: 'What you say the first time you meet someone.',
      unit: 3,
      stage: 'P0',
      fn: 'introducing',
      slots: [],
      examples: ['Nice to meet you.', 'Nice to meet you too.'],
      requires: ['myNameIs'],
      reply: 'Nice to meet you too.',
      show: 'situation',
    },
    {
      id: 'imFrom',
      chunk: 'I’m from ___.',
      say: 'I’m from Israel.',
      meaning: 'Saying which country or city you come from.',
      unit: 3,
      stage: 'P1',
      fn: 'introducing',
      slots: ['Israel', 'Russia', 'Spain', 'France', 'Ukraine'],
      examples: ['I’m from Israel.', 'I’m from Moscow.', 'I’m from a small town.'],
      requires: ['myNameIs'],
      reply: 'Oh, nice!',
      show: 'picture',
    },
    {
      id: 'whereAreYouFrom',
      chunk: 'Where are you from?',
      say: 'Where are you from?',
      meaning: 'Asking which country or city someone comes from.',
      unit: 3,
      stage: 'P1',
      fn: 'introducing',
      slots: [],
      examples: ['Where are you from?', 'And where are you from?'],
      requires: ['imFrom'],
      reply: 'I’m from…',
      show: 'picture',
    },
    {
      id: 'iLiveIn',
      chunk: 'I live in ___.',
      say: 'I live in Tel Aviv.',
      meaning: 'Saying where your home is now.',
      unit: 3,
      stage: 'P1',
      fn: 'introducing',
      slots: ['Tel Aviv', 'Haifa', 'Madrid', 'a small town', 'the city'],
      examples: ['I live in Tel Aviv.', 'I live in a small town.', 'I live here.'],
      requires: ['imFrom'],
      show: 'picture',
    },
    {
      id: 'imYearsOld',
      chunk: 'I’m ___ years old.',
      say: 'I’m thirty years old.',
      meaning: 'Saying your age.',
      unit: 3,
      stage: 'P1',
      fn: 'introducing',
      slots: ['six', 'eight', 'thirty', 'forty', 'sixty-eight'],
      examples: ['I’m six years old.', 'I’m thirty years old.', 'I’m sixty-eight.'],
      requires: ['myNameIs'],
      show: 'gesture',
    },
    {
      id: 'howOldAreYou',
      chunk: 'How old are you?',
      say: 'How old are you?',
      meaning: 'Asking someone’s age.',
      unit: 3,
      stage: 'P1',
      fn: 'introducing',
      slots: [],
      examples: ['How old are you?', 'And how old are you?'],
      requires: ['imYearsOld'],
      reply: 'I’m … years old.',
      show: 'gesture',
    },
    {
      id: 'iSpeak',
      chunk: 'I speak ___.',
      say: 'I speak Hebrew and a little English.',
      meaning: 'Saying which languages you can use.',
      unit: 3,
      stage: 'P1',
      fn: 'introducing',
      slots: ['Hebrew', 'Russian', 'Spanish', 'French', 'a little English'],
      examples: ['I speak Hebrew.', 'I speak Russian and a little English.'],
      requires: ['myNameIs'],
      show: 'situation',
    },
    {
      id: 'thisIs',
      chunk: 'This is ___.',
      say: 'This is my wife, Anna.',
      meaning: 'Introducing another person, or naming a thing.',
      unit: 3,
      stage: 'P1',
      fn: 'introducing',
      slots: ['my wife', 'my husband', 'my son', 'my friend', 'my teacher'],
      examples: ['This is my friend, Sam.', 'This is my son.', 'This is my house.'],
      requires: ['myNameIs'],
      reply: 'Nice to meet you.',
      show: 'gesture',
    },
  ],

  /* ====================== 4. Talking about yourself ======================= *
     "I like ___" and "I have ___" are the two frames that carry more early
     conversation than anything else in the language, so both arrive with
     their negatives immediately — a learner who can only agree is not yet
     having a conversation.                                                    */
  [
    {
      id: 'iLike',
      chunk: 'I like ___.',
      say: 'I like coffee.',
      meaning: 'Saying something is good for you — you enjoy it.',
      unit: 4,
      stage: 'P1',
      fn: 'describingSelf',
      slots: ['coffee', 'music', 'football', 'this city', 'my job'],
      examples: ['I like coffee.', 'I like music.', 'I like my job.'],
      requires: [],
      reply: 'Me too!',
      show: 'picture',
    },
    {
      id: 'iDontLike',
      chunk: 'I don’t like ___.',
      say: 'I don’t like coffee.',
      meaning: 'Saying something is not good for you.',
      unit: 4,
      stage: 'P1',
      fn: 'describingSelf',
      slots: ['coffee', 'the cold', 'this weather', 'tomatoes'],
      examples: ['I don’t like coffee.', 'I don’t like the cold.'],
      requires: ['iLike'],
      show: 'contrast',
    },
    {
      id: 'iLove',
      chunk: 'I love ___.',
      say: 'I love my grandchildren.',
      meaning: 'Saying you like something very much.',
      unit: 4,
      stage: 'P1',
      fn: 'describingSelf',
      slots: ['my family', 'my grandchildren', 'this song', 'the sea'],
      examples: ['I love my family.', 'I love this song.'],
      requires: ['iLike'],
      show: 'contrast',
    },
    {
      id: 'iHave',
      chunk: 'I have ___.',
      say: 'I have two children.',
      meaning: 'Saying what belongs to you or what you own.',
      unit: 4,
      stage: 'P1',
      fn: 'describingSelf',
      slots: ['two children', 'a dog', 'a car', 'a question', 'time'],
      examples: ['I have two children.', 'I have a dog.', 'I have a question.'],
      requires: [],
      show: 'object',
    },
    {
      id: 'iDontHave',
      chunk: 'I don’t have ___.',
      say: 'I don’t have a car.',
      meaning: 'Saying you do not own or hold something.',
      unit: 4,
      stage: 'P1',
      fn: 'describingSelf',
      slots: ['a car', 'time', 'money', 'a pen'],
      examples: ['I don’t have a car.', 'I don’t have time today.'],
      requires: ['iHave'],
      show: 'contrast',
    },
    {
      id: 'imA',
      chunk: 'I’m a ___.',
      say: 'I’m a teacher.',
      meaning: 'Saying your job or what you are.',
      unit: 4,
      stage: 'P1',
      fn: 'describingSelf',
      slots: ['teacher', 'driver', 'nurse', 'student', 'engineer'],
      examples: ['I’m a teacher.', 'I’m a student.', 'I’m a nurse.'],
      requires: ['myNameIs'],
      show: 'picture',
    },
    {
      id: 'whatDoYouDo',
      chunk: 'What do you do?',
      say: 'What do you do?',
      meaning: 'Asking someone about their job.',
      unit: 4,
      stage: 'P2',
      fn: 'describingSelf',
      slots: [],
      examples: ['What do you do?', 'And what do you do?'],
      requires: ['imA'],
      reply: 'I’m a…',
      show: 'situation',
    },
    {
      id: 'iWorkAt',
      chunk: 'I work at ___.',
      say: 'I work at a hospital.',
      meaning: 'Saying where you work.',
      unit: 4,
      stage: 'P2',
      fn: 'describingSelf',
      slots: ['a hospital', 'a school', 'home', 'a shop', 'an office'],
      examples: ['I work at a school.', 'I work at home.'],
      requires: ['imA'],
      show: 'picture',
    },
    {
      id: 'myFavourite',
      /* One gap, not two. "My favourite ___ is ___." is the fuller pattern,
         but a beginner meets this the moment somebody asks "what's your
         favourite colour?" — the category is already on the table, and a
         frame with a single slot is one they can actually fill in real time. */
      chunk: 'My favourite is ___.',
      say: 'My favourite is blue.',
      meaning: 'Saying which one you like best.',
      unit: 4,
      stage: 'P2',
      fn: 'describingSelf',
      slots: ['blue', 'soup', 'Sunday', 'my dog', 'the sea'],
      examples: ['My favourite is blue.', 'My favourite is Sunday.', 'My favourite is soup.'],
      requires: ['iLike'],
      show: 'picture',
    },
    {
      id: 'imLearningEnglish',
      chunk: 'I’m learning English.',
      say: 'I’m learning English.',
      meaning: 'Telling someone why your English is still small — and it works.',
      unit: 4,
      stage: 'P1',
      fn: 'describingSelf',
      slots: [],
      examples: ['I’m learning English.', 'I’m learning English now.'],
      requires: ['myNameIs'],
      reply: 'That’s great!',
      show: 'situation',
    },
  ],

  /* ========================= 5. Wants and needs =========================== *
     The unit that turns a learner from someone being taught into someone
     getting things done. "Can I have ___, please?" is the highest-value
     single frame in the whole inventory: it works in a shop, a café, a
     pharmacy, an office and a classroom without changing a word.              */
  [
    {
      id: 'iWant',
      chunk: 'I want ___.',
      say: 'I want water.',
      meaning: 'Saying what you would like to have or do.',
      unit: 5,
      stage: 'P1',
      fn: 'wanting',
      slots: ['water', 'coffee', 'a ticket', 'to go home', 'to try again'],
      examples: ['I want water.', 'I want to go home.', 'I want to try again.'],
      requires: [],
      show: 'object',
    },
    {
      id: 'iNeed',
      chunk: 'I need ___.',
      say: 'I need help.',
      meaning: 'Saying what you must have — stronger than “want”.',
      unit: 5,
      stage: 'P1',
      fn: 'wanting',
      slots: ['help', 'a doctor', 'my phone', 'more time', 'to sit down'],
      examples: ['I need help.', 'I need a doctor.', 'I need more time.'],
      requires: ['iWant'],
      show: 'contrast',
    },
    {
      id: 'idLike',
      chunk: 'I’d like ___, please.',
      say: 'I’d like a coffee, please.',
      meaning: 'The polite way to say what you want. Use it with strangers.',
      unit: 5,
      stage: 'P2',
      fn: 'wanting',
      slots: ['a coffee', 'the bill', 'two tickets', 'a small one'],
      examples: ['I’d like a coffee, please.', 'I’d like two tickets, please.'],
      requires: ['iWant', 'please'],
      reply: 'Of course.',
      show: 'contrast',
    },
    {
      id: 'canIHave',
      chunk: 'Can I have ___, please?',
      say: 'Can I have a coffee, please?',
      meaning: 'Asking someone to give you something, politely.',
      unit: 5,
      stage: 'P1',
      fn: 'wanting',
      slots: ['a coffee', 'the menu', 'some water', 'a bag', 'your name'],
      examples: ['Can I have some water, please?', 'Can I have the menu, please?'],
      requires: ['please'],
      reply: 'Here you are.',
      show: 'object',
    },
    {
      id: 'doYouHave',
      chunk: 'Do you have ___?',
      say: 'Do you have coffee?',
      meaning: 'Asking whether someone has something.',
      unit: 5,
      stage: 'P1',
      fn: 'wanting',
      slots: ['coffee', 'a pen', 'a smaller one', 'time', 'children'],
      examples: ['Do you have coffee?', 'Do you have a pen?', 'Do you have children?'],
      requires: ['iHave'],
      reply: 'Yes, we do. / No, sorry.',
      show: 'object',
    },
    {
      id: 'iDontWant',
      chunk: 'I don’t want ___.',
      say: 'I don’t want sugar, thank you.',
      meaning: 'Refusing something clearly and politely.',
      unit: 5,
      stage: 'P1',
      fn: 'wanting',
      slots: ['sugar', 'milk', 'more', 'a bag'],
      examples: ['I don’t want sugar, thank you.', 'No, thank you. I don’t want more.'],
      requires: ['iWant'],
      show: 'contrast',
    },
    {
      id: 'canYouHelpMe',
      chunk: 'Can you help me, please?',
      say: 'Can you help me, please?',
      meaning: 'Asking someone for help.',
      unit: 5,
      stage: 'P1',
      fn: 'wanting',
      slots: [],
      examples: ['Can you help me, please?', 'Excuse me — can you help me, please?'],
      requires: ['excuseMe', 'please'],
      reply: 'Of course.',
      show: 'situation',
    },
    {
      id: 'imHungry',
      chunk: 'I’m ___.',
      say: 'I’m hungry.',
      meaning: 'Saying how your body feels right now.',
      unit: 5,
      stage: 'P1',
      fn: 'wanting',
      slots: ['hungry', 'thirsty', 'tired', 'cold', 'hot', 'OK'],
      examples: ['I’m hungry.', 'I’m tired.', 'I’m cold.'],
      requires: [],
      show: 'gesture',
    },
    {
      id: 'iHaveToGo',
      chunk: 'I have to go.',
      say: 'Sorry, I have to go.',
      meaning: 'Ending a conversation because you must leave.',
      unit: 5,
      stage: 'P2',
      fn: 'wanting',
      slots: [],
      examples: ['I have to go.', 'Sorry, I have to go now.'],
      requires: ['goodbye'],
      reply: 'OK — see you!',
      show: 'situation',
    },
    {
      id: 'lets',
      chunk: 'Let’s ___.',
      say: 'Let’s go.',
      meaning: 'Suggesting that you and the other person do something together.',
      unit: 5,
      stage: 'P2',
      fn: 'wanting',
      slots: ['go', 'start', 'try again', 'eat', 'sit down'],
      examples: ['Let’s go.', 'Let’s try again.', 'Let’s eat.'],
      requires: [],
      reply: 'OK!',
      show: 'gesture',
    },
  ],

  /* ========================== 6. Basic questions ========================== *
     One frame per question word, so the learner leaves with the machine
     rather than a list of questions. Every one of them is answerable by
     pointing, which is what makes them teachable at P1.                       */
  [
    {
      id: 'whatIsThis',
      chunk: 'What is this?',
      say: 'What is this?',
      meaning: 'Asking the name of a thing you can see.',
      unit: 6,
      stage: 'P0',
      fn: 'asking',
      slots: [],
      examples: ['What is this?', 'What’s this?', 'And what is that?'],
      requires: [],
      reply: 'It’s a…',
      show: 'object',
    },
    {
      id: 'whereIs',
      chunk: 'Where is ___?',
      say: 'Where is the bathroom?',
      meaning: 'Asking about the place something is in.',
      unit: 6,
      stage: 'P1',
      fn: 'asking',
      slots: ['the bathroom', 'the station', 'the exit', 'my bag', 'the doctor'],
      examples: ['Where is the bathroom?', 'Where is the station?', 'Where’s my bag?'],
      requires: ['excuseMe'],
      reply: 'It’s over there.',
      show: 'gesture',
    },
    {
      id: 'whenIs',
      chunk: 'When is ___?',
      say: 'When is the next bus?',
      meaning: 'Asking about the time something happens.',
      unit: 6,
      stage: 'P2',
      fn: 'asking',
      slots: ['the next bus', 'the lesson', 'the meeting', 'your birthday'],
      examples: ['When is the next bus?', 'When is the lesson?'],
      requires: ['whereIs'],
      show: 'picture',
    },
    {
      id: 'whoIsThat',
      chunk: 'Who is that?',
      say: 'Who is that?',
      meaning: 'Asking about a person.',
      unit: 6,
      stage: 'P1',
      fn: 'asking',
      slots: [],
      examples: ['Who is that?', 'Who’s that?', 'Who is she?'],
      requires: ['whatIsThis'],
      reply: 'That’s my…',
      show: 'picture',
    },
    {
      id: 'howMuch',
      chunk: 'How much is ___?',
      say: 'How much is this?',
      meaning: 'Asking the price.',
      unit: 6,
      stage: 'P1',
      fn: 'asking',
      slots: ['this', 'that', 'the ticket', 'the coffee'],
      examples: ['How much is this?', 'How much is the ticket?'],
      requires: ['whatIsThis'],
      reply: 'It’s ten.',
      show: 'object',
    },
    {
      id: 'whatTime',
      chunk: 'What time is it?',
      say: 'What time is it?',
      meaning: 'Asking for the time now.',
      unit: 6,
      stage: 'P2',
      fn: 'asking',
      slots: [],
      examples: ['What time is it?', 'Excuse me, what time is it?'],
      requires: ['excuseMe'],
      reply: 'It’s three o’clock.',
      show: 'object',
    },
    {
      id: 'why',
      chunk: 'Why?',
      say: 'Why?',
      meaning: 'Asking for the reason.',
      unit: 6,
      stage: 'P1',
      fn: 'asking',
      slots: [],
      examples: ['Why?', 'Why not?', 'But why?'],
      requires: [],
      reply: 'Because…',
      show: 'situation',
    },
    {
      id: 'whichOne',
      chunk: 'Which one?',
      say: 'Which one?',
      meaning: 'Asking someone to choose between things you can see.',
      unit: 6,
      stage: 'P2',
      fn: 'asking',
      slots: [],
      examples: ['Which one?', 'Which one do you want?', 'This one or that one?'],
      requires: ['whatIsThis'],
      reply: 'This one, please.',
      show: 'contrast',
    },
    {
      id: 'canI',
      chunk: 'Can I ___?',
      say: 'Can I sit here?',
      meaning: 'Asking permission to do something.',
      unit: 6,
      stage: 'P2',
      fn: 'asking',
      slots: ['sit here', 'come in', 'try', 'ask a question', 'pay now'],
      examples: ['Can I sit here?', 'Can I come in?', 'Can I ask a question?'],
      requires: ['canIHave'],
      reply: 'Yes, of course.',
      show: 'gesture',
    },
    {
      id: 'doYouLike',
      chunk: 'Do you like ___?',
      say: 'Do you like coffee?',
      meaning: 'Asking someone what they enjoy.',
      unit: 6,
      stage: 'P1',
      fn: 'asking',
      slots: ['coffee', 'music', 'your job', 'this city', 'football'],
      examples: ['Do you like coffee?', 'Do you like your job?'],
      requires: ['iLike'],
      reply: 'Yes, I do. / No, I don’t.',
      show: 'picture',
    },
  ],

  /* ========================= 7. Everyday actions ========================== */
  [
    {
      id: 'imGoingTo',
      chunk: 'I’m going to ___.',
      say: 'I’m going to the shop.',
      meaning: 'Saying where you are going, or what you will do next.',
      unit: 7,
      stage: 'P2',
      fn: 'everyday',
      slots: ['the shop', 'work', 'home', 'the doctor', 'sleep'],
      examples: ['I’m going to the shop.', 'I’m going home.', 'I’m going to sleep.'],
      requires: ['iWant'],
      show: 'gesture',
    },
    {
      id: 'imDoing',
      /* The slot fillers are already inflected ('working', 'eating', …), so the
         chunk must not add its own '-ing' — `fillSlot` would otherwise produce
         "I'm workinging." */
      chunk: 'I’m ___.',
      say: 'I’m working.',
      meaning: 'Saying what you are doing right now.',
      unit: 7,
      stage: 'P2',
      fn: 'everyday',
      slots: ['working', 'eating', 'reading', 'waiting', 'learning'],
      examples: ['I’m working.', 'I’m eating.', 'I’m waiting.'],
      requires: [],
      show: 'gesture',
    },
    {
      id: 'everyDay',
      chunk: 'I ___ every day.',
      say: 'I walk every day.',
      meaning: 'Saying what you do as a habit.',
      unit: 7,
      stage: 'P2',
      fn: 'everyday',
      slots: ['walk', 'work', 'cook', 'study', 'read'],
      examples: ['I walk every day.', 'I work every day.', 'I cook every day.'],
      requires: ['imDoing'],
      show: 'picture',
    },
    {
      id: 'iCan',
      chunk: 'I can ___.',
      say: 'I can drive.',
      meaning: 'Saying what you are able to do.',
      unit: 7,
      stage: 'P1',
      fn: 'everyday',
      slots: ['drive', 'cook', 'swim', 'help you', 'come tomorrow'],
      examples: ['I can drive.', 'I can help you.', 'I can come tomorrow.'],
      requires: [],
      show: 'gesture',
    },
    {
      id: 'iCant',
      chunk: 'I can’t ___.',
      say: 'I can’t drive.',
      meaning: 'Saying what you are not able to do.',
      unit: 7,
      stage: 'P1',
      fn: 'everyday',
      slots: ['drive', 'come today', 'hear you', 'read this', 'stay'],
      examples: ['I can’t drive.', 'I can’t come today.', 'I can’t hear you.'],
      requires: ['iCan'],
      show: 'contrast',
    },
    {
      id: 'imLookingFor',
      chunk: 'I’m looking for ___.',
      say: 'I’m looking for the station.',
      meaning: 'Saying what you are trying to find.',
      unit: 7,
      stage: 'P2',
      fn: 'everyday',
      slots: ['the station', 'my keys', 'a pharmacy', 'this address'],
      examples: ['I’m looking for the station.', 'I’m looking for my keys.'],
      requires: ['whereIs'],
      reply: 'It’s over there.',
      show: 'situation',
    },
    {
      id: 'letsGo',
      chunk: 'Let’s go.',
      say: 'Let’s go.',
      meaning: 'Telling someone it is time to leave together.',
      unit: 7,
      stage: 'P1',
      fn: 'everyday',
      slots: [],
      examples: ['Let’s go.', 'OK — let’s go!'],
      requires: ['lets'],
      show: 'gesture',
    },
    {
      id: 'waitAMinute',
      chunk: 'Wait a minute.',
      say: 'Wait a minute, please.',
      meaning: 'Asking someone to stop and wait for you.',
      unit: 7,
      stage: 'P1',
      fn: 'everyday',
      slots: [],
      examples: ['Wait a minute.', 'Wait a minute, please.'],
      requires: ['oneMoment'],
      show: 'gesture',
    },
    {
      id: 'iForgot',
      chunk: 'I forgot.',
      say: 'Sorry, I forgot.',
      meaning: 'Saying that something left your memory.',
      unit: 7,
      stage: 'P2',
      fn: 'everyday',
      slots: [],
      examples: ['I forgot.', 'Sorry, I forgot.', 'I forgot the word.'],
      requires: ['sorry'],
      show: 'situation',
    },
    {
      id: 'iDont',
      chunk: 'I don’t ___.',
      say: 'I don’t drive.',
      meaning: 'Saying something is not what you do.',
      unit: 7,
      stage: 'P2',
      fn: 'everyday',
      slots: ['drive', 'smoke', 'eat meat', 'work on Sunday'],
      examples: ['I don’t drive.', 'I don’t eat meat.', 'I don’t work on Sunday.'],
      requires: ['iDontLike'],
      show: 'contrast',
    },
  ],

  /* ====================== 8. Conversation reactions ======================= *
     What stops a beginner's conversation from dying between turns. These are
     tiny, they are almost all one or two words, and they buy the learner more
     conversational room than any grammar point at this level.                 */
  [
    {
      id: 'really',
      chunk: 'Really?',
      say: 'Really?',
      meaning: 'Showing you are interested and want to hear more.',
      unit: 8,
      stage: 'P1',
      fn: 'reacting',
      slots: [],
      examples: ['Really?', 'Oh, really?'],
      requires: [],
      show: 'situation',
    },
    {
      id: 'thatsGreat',
      chunk: 'That’s great!',
      say: 'That’s great!',
      meaning: 'Reacting to good news.',
      unit: 8,
      stage: 'P1',
      fn: 'reacting',
      slots: [],
      examples: ['That’s great!', 'That’s wonderful!', 'That’s very good.'],
      requires: [],
      show: 'situation',
    },
    {
      id: 'ohNo',
      chunk: 'Oh no!',
      say: 'Oh no! I’m sorry.',
      meaning: 'Reacting to bad news.',
      unit: 8,
      stage: 'P1',
      fn: 'reacting',
      slots: [],
      examples: ['Oh no!', 'Oh no — I’m sorry.'],
      requires: ['sorry'],
      show: 'contrast',
    },
    {
      id: 'meToo',
      chunk: 'Me too.',
      say: 'Me too.',
      meaning: 'Saying the same is true for you.',
      unit: 8,
      stage: 'P1',
      fn: 'reacting',
      slots: [],
      examples: ['Me too.', 'Me too! I like it.'],
      requires: ['iLike'],
      show: 'gesture',
    },
    {
      id: 'iThinkSo',
      chunk: 'I think so.',
      say: 'I think so.',
      meaning: 'Saying you believe it is true, but you are not sure.',
      unit: 8,
      stage: 'P2',
      fn: 'reacting',
      slots: [],
      examples: ['I think so.', 'Yes, I think so.'],
      requires: [],
      show: 'situation',
    },
    {
      id: 'iDontThinkSo',
      chunk: 'I don’t think so.',
      say: 'I don’t think so.',
      meaning: 'Saying no politely, when you are not certain.',
      unit: 8,
      stage: 'P2',
      fn: 'reacting',
      slots: [],
      examples: ['I don’t think so.', 'No, I don’t think so.'],
      requires: ['iThinkSo'],
      show: 'contrast',
    },
    {
      id: 'iAgree',
      chunk: 'I agree.',
      say: 'I agree.',
      meaning: 'Saying you think the same.',
      unit: 8,
      stage: 'P2',
      fn: 'reacting',
      slots: [],
      examples: ['I agree.', 'Yes, I agree.'],
      requires: [],
      show: 'gesture',
    },
    {
      id: 'goodIdea',
      chunk: 'That’s a good idea.',
      say: 'That’s a good idea.',
      meaning: 'Saying you like what the other person suggested.',
      unit: 8,
      stage: 'P2',
      fn: 'reacting',
      slots: [],
      examples: ['That’s a good idea.', 'Good idea!'],
      requires: ['lets'],
      show: 'situation',
    },
    {
      id: 'andYou',
      chunk: 'And you?',
      say: 'And you?',
      meaning: 'Giving the question back — the cheapest way to keep talking.',
      unit: 8,
      stage: 'P1',
      fn: 'reacting',
      slots: [],
      examples: ['And you?', 'I’m fine, thanks. And you?'],
      requires: ['imFine'],
      show: 'gesture',
    },
    {
      id: 'ofCourse',
      chunk: 'Of course.',
      say: 'Of course.',
      meaning: 'A warm “yes” to a request.',
      unit: 8,
      stage: 'P2',
      fn: 'reacting',
      slots: [],
      examples: ['Of course.', 'Of course — here you are.'],
      requires: ['canYouHelpMe'],
      show: 'situation',
    },
  ],

  /* ======================= 9. Practical situations ======================== */
  [
    {
      id: 'onePlease',
      chunk: 'One ___, please.',
      say: 'One coffee, please.',
      meaning: 'Ordering or buying — the shortest thing that works.',
      unit: 9,
      stage: 'P1',
      fn: 'practical',
      slots: ['coffee', 'ticket', 'bag', 'water'],
      examples: ['One coffee, please.', 'Two tickets, please.'],
      requires: ['please'],
      reply: 'Here you are.',
      show: 'object',
    },
    {
      id: 'hereYouAre',
      chunk: 'Here you are.',
      say: 'Here you are.',
      meaning: 'What you say as you hand something over.',
      unit: 9,
      stage: 'P1',
      fn: 'practical',
      slots: [],
      examples: ['Here you are.', 'Here you are — thank you.'],
      requires: ['thankYou'],
      reply: 'Thank you.',
      show: 'object',
    },
    {
      id: 'canIPayByCard',
      chunk: 'Can I pay by card?',
      say: 'Can I pay by card?',
      meaning: 'Asking whether you can use a bank card.',
      unit: 9,
      stage: 'P2',
      fn: 'practical',
      slots: [],
      examples: ['Can I pay by card?', 'Can I pay by card, please?'],
      requires: ['canI'],
      reply: 'Yes, of course.',
      show: 'object',
    },
    {
      id: 'isThereNearHere',
      chunk: 'Is there a ___ near here?',
      say: 'Is there a pharmacy near here?',
      meaning: 'Asking whether something exists close by.',
      unit: 9,
      stage: 'P2',
      fn: 'practical',
      slots: ['pharmacy', 'bank', 'supermarket', 'bus stop', 'doctor'],
      examples: ['Is there a pharmacy near here?', 'Is there a bank near here?'],
      requires: ['whereIs'],
      reply: 'Yes — over there.',
      show: 'gesture',
    },
    {
      id: 'howDoIGetTo',
      chunk: 'How do I get to ___?',
      say: 'How do I get to the station?',
      meaning: 'Asking for directions to a place.',
      unit: 9,
      stage: 'P3',
      fn: 'practical',
      slots: ['the station', 'the airport', 'the city centre', 'this address'],
      examples: ['How do I get to the station?', 'How do I get to the airport?'],
      requires: ['whereIs'],
      show: 'picture',
    },
    {
      id: 'writeItDown',
      chunk: 'Can you write it down, please?',
      say: 'Can you write it down, please?',
      meaning: 'Asking someone to put it on paper so you can read it slowly.',
      unit: 9,
      stage: 'P2',
      fn: 'practical',
      slots: [],
      examples: ['Can you write it down, please?', 'Please write it down.'],
      requires: ['sayAgain'],
      show: 'gesture',
    },
    {
      id: 'iHaveAnAppointment',
      chunk: 'I have an appointment at ___.',
      say: 'I have an appointment at three.',
      meaning: 'Telling a receptionist you are expected.',
      unit: 9,
      stage: 'P3',
      fn: 'practical',
      slots: ['three', 'ten', 'two o’clock', 'nine thirty'],
      examples: ['I have an appointment at three.', 'I have an appointment at ten.'],
      requires: ['iHave', 'whatTime'],
      show: 'situation',
    },
    {
      id: 'iDontFeelWell',
      chunk: 'I don’t feel well.',
      say: 'I don’t feel well.',
      meaning: 'Telling someone you are ill.',
      unit: 9,
      stage: 'P2',
      fn: 'practical',
      slots: [],
      examples: ['I don’t feel well.', 'I don’t feel well today.'],
      requires: ['imHungry'],
      reply: 'I’m sorry. Do you need a doctor?',
      show: 'gesture',
    },
    {
      id: 'itDoesntWork',
      chunk: 'It doesn’t work.',
      say: 'It doesn’t work.',
      meaning: 'Saying a thing is broken or not doing its job.',
      unit: 9,
      stage: 'P2',
      fn: 'practical',
      slots: [],
      examples: ['It doesn’t work.', 'Sorry — it doesn’t work.'],
      requires: [],
      show: 'object',
    },
    {
      id: 'imJustLooking',
      chunk: 'I’m just looking, thank you.',
      say: 'I’m just looking, thank you.',
      meaning: 'Politely telling a shop assistant you do not need help yet.',
      unit: 9,
      stage: 'P3',
      fn: 'practical',
      slots: [],
      examples: ['I’m just looking, thank you.', 'Just looking, thanks.'],
      requires: ['thankYou'],
      show: 'situation',
    },
  ],

  /* ====================== 10. Simple social planning ====================== *
     The point the learner stops surviving in English and starts having a
     social life in it: making a plan, and — just as important — turning one
     down without disappearing.                                                */
  [
    {
      id: 'areYouFreeOn',
      chunk: 'Are you free on ___?',
      say: 'Are you free on Sunday?',
      meaning: 'Asking if someone has time on a day.',
      unit: 10,
      stage: 'P3',
      fn: 'arranging',
      slots: ['Sunday', 'Monday', 'Friday', 'the weekend'],
      examples: ['Are you free on Sunday?', 'Are you free on Friday?'],
      requires: ['doYouHave'],
      reply: 'Yes, I am. / Sorry, I can’t.',
      show: 'picture',
    },
    {
      id: 'wouldYouLikeTo',
      chunk: 'Would you like to ___?',
      say: 'Would you like to have coffee?',
      meaning: 'Inviting someone politely.',
      unit: 10,
      stage: 'P3',
      fn: 'arranging',
      slots: ['have coffee', 'come with me', 'meet on Sunday', 'try'],
      examples: ['Would you like to have coffee?', 'Would you like to come with me?'],
      requires: ['idLike'],
      reply: 'Yes, I’d love to.',
      show: 'situation',
    },
    {
      id: 'letsMeetAt',
      chunk: 'Let’s meet at ___.',
      say: 'Let’s meet at six.',
      meaning: 'Suggesting a time or a place to meet.',
      unit: 10,
      stage: 'P3',
      fn: 'arranging',
      slots: ['six', 'the station', 'the café', 'my house'],
      examples: ['Let’s meet at six.', 'Let’s meet at the station.'],
      requires: ['lets'],
      reply: 'OK — see you there.',
      show: 'situation',
    },
    {
      id: 'whatTimeQ',
      chunk: 'What time?',
      say: 'What time?',
      meaning: 'Asking for the time of a plan.',
      unit: 10,
      stage: 'P2',
      fn: 'arranging',
      slots: [],
      examples: ['What time?', 'What time is good for you?'],
      requires: ['whatTime'],
      show: 'situation',
    },
    {
      id: 'thatWorksForMe',
      chunk: 'That works for me.',
      say: 'That works for me.',
      meaning: 'Agreeing to a plan.',
      unit: 10,
      stage: 'P3',
      fn: 'arranging',
      slots: [],
      examples: ['That works for me.', 'Yes, that works for me.'],
      requires: ['iAgree'],
      show: 'situation',
    },
    {
      id: 'sorryICant',
      chunk: 'Sorry, I can’t.',
      say: 'Sorry, I can’t on Sunday.',
      meaning: 'Saying no to a plan, kindly.',
      unit: 10,
      stage: 'P2',
      fn: 'arranging',
      slots: [],
      examples: ['Sorry, I can’t.', 'Sorry, I can’t on Sunday.'],
      requires: ['iCant'],
      show: 'contrast',
    },
    {
      id: 'maybeNextTime',
      chunk: 'Maybe next time.',
      say: 'Maybe next time.',
      meaning: 'Keeping the door open after you say no.',
      unit: 10,
      stage: 'P3',
      fn: 'arranging',
      slots: [],
      examples: ['Maybe next time.', 'Sorry — maybe next time.'],
      requires: ['sorryICant'],
      show: 'situation',
    },
    {
      id: 'canWeMakeItLater',
      chunk: 'Can we make it later?',
      say: 'Can we make it later?',
      meaning: 'Asking to move a plan to a later time.',
      unit: 10,
      stage: 'P3',
      fn: 'arranging',
      slots: [],
      examples: ['Can we make it later?', 'Can we make it a bit later?'],
      requires: ['canI'],
      show: 'situation',
    },
    {
      id: 'seeYouOn',
      chunk: 'See you on ___.',
      say: 'See you on Sunday.',
      meaning: 'Saying goodbye when you already have a plan.',
      unit: 10,
      stage: 'P2',
      fn: 'arranging',
      slots: ['Sunday', 'Monday', 'Friday', 'Tuesday'],
      examples: ['See you on Sunday.', 'See you tomorrow.', 'See you next week.'],
      requires: ['goodbye'],
      show: 'gesture',
    },
    {
      id: 'illCallYou',
      chunk: 'I’ll call you.',
      say: 'I’ll call you tomorrow.',
      meaning: 'Promising to telephone someone.',
      unit: 10,
      stage: 'P3',
      fn: 'arranging',
      slots: [],
      examples: ['I’ll call you.', 'I’ll call you tomorrow.'],
      requires: ['iCan'],
      reply: 'OK, thank you!',
      show: 'gesture',
    },
  ],
]

/** The whole inventory, in teaching order. */
export const phraseCurriculum: PhraseTarget[] = UNITS.flat().map((p, i) => ({
  ...p,
  order: i,
}))

const BY_ID = new Map(phraseCurriculum.map((p) => [p.id, p]))

export function getPhrase(id: string): PhraseTarget | undefined {
  return BY_ID.get(id)
}

export function phrasesForUnit(unit: number): PhraseTarget[] {
  return phraseCurriculum.filter((p) => p.unit === unit)
}

/** Unit titles, for the tutor. Localized via `curriculum.unit.<n>`. */
export const PHRASE_UNITS: { unit: number; title: string; fn: PhraseFunction }[] = [
  { unit: 1, title: 'Meeting people', fn: 'greeting' },
  { unit: 2, title: 'When you don’t understand', fn: 'repair' },
  { unit: 3, title: 'Introducing yourself', fn: 'introducing' },
  { unit: 4, title: 'Talking about yourself', fn: 'describingSelf' },
  { unit: 5, title: 'Asking for what you need', fn: 'wanting' },
  { unit: 6, title: 'Asking questions', fn: 'asking' },
  { unit: 7, title: 'Everyday actions', fn: 'everyday' },
  { unit: 8, title: 'Keeping a conversation going', fn: 'reacting' },
  { unit: 9, title: 'Out in the world', fn: 'practical' },
  { unit: 10, title: 'Making plans', fn: 'arranging' },
]
